# Generated by Django 4.1.2 on 2022-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='price',
            field=models.TextField(),
        ),
    ]
