# Generated by Django 4.1.2 on 2022-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_alter_films_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='movie_lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='movie_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='price',
            field=models.IntegerField(),
        ),
    ]
