# Generated by Django 4.1.2 on 2022-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0003_films_movie_lang_films_movie_year_films_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='show_times',
        ),
        migrations.AddField(
            model_name='films',
            name='showtime1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
