# Generated by Django 4.1.2 on 2022-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0004_remove_films_show_times_films_showtime1'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='showtime2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='showtime3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='showtime1',
            field=models.TimeField(),
        ),
    ]
