# Generated by Django 4.1.2 on 2022-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0005_films_showtime2_films_showtime3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
