# Generated by Django 4.1.2 on 2022-11-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0006_alter_films_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='films',
            new_name='film',
        ),
    ]
