# Generated by Django 4.1.2 on 2022-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0007_rename_films_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
