# Generated by Django 4.1.2 on 2022-11-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0009_film_deleted_alter_film_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
