# Generated by Django 4.1.2 on 2022-11-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_users_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
